# Generated by Django 3.2.5 on 2021-07-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_backend', '0002_auto_20210713_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
    ]
